name: Automated CalVer Tagging

concurrency:  
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Tag
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          VERSION=v$(date +'%Y.%-m').$GITHUB_RUN_NUMBER+$(git rev-parse --short HEAD)
          # Store the tag name in an environment variable for later use/steps
          echo "TAG_NAME=$VERSION" >> $GITHUB_ENV
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION" --tags
